# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-async]
github = "mafredri/zsh-async"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.zsh-abbrev]
github = "olets/zsh-abbr"
use = ["zsh-abbr.zsh"]

[plugins.fzf]
github = "junegunn/fzf"

# syntax-highlighting は最後に読み込む
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-functions]
local = "~/.config/zsh"
use = ["*.zsh"]
